{% set version = "0.0.8" %}

package: 
  name: atlas-data-import
  version: '{{ version }}'

source:
  url: https://github.com/ebi-gene-expression-group/atlas-data-import/archive/{{ version }}.tar.gz
  sha256: d385ceb10ef203ea4d555d93c89fc127d4f441ea0adae4baed6358d6dd821a8f

build:
  number: 0
  noarch: generic

requirements:
    run:
      - r-base
      - r-r.utils
      - r-yaml
      - r-optparse
      - r-workflowscriptscommon
      - r-rcurl
      
test:
    commands:
      - get_experiment_data.R --help
      - import_classifiers.R --help
      - import_sdrf_files.R --help
      
about:
  home: https://github.com/ebi-gene-expression-group/atlas-data-import
  license: MIT
  summary: Scripts for extracting expression- and metadata from Single Cell Expression Atlas in a programmatic way.
  
