{% set version = "2.0.3" %}
{% set name = "mzToSQLite" %}

package:
  name: mztosqlite
  version: {{ version }}

build:
  noarch: generic
  number: 0

source:
  url: https://github.com/galaxyproteomics/mzToSQLite/releases/download/{{ version }}/{{ name }}-{{ version }}.jar
  sha256: 56d5544dabfcfc24f779d57d14eaf56a79e67ca489e3a1ac856632737b1ad1d6

requirements:
  host:
    - python
  run:
    - python
    - openjdk >=8

test:
  commands:
    - mz_to_sqlite -h

about:
  home: https://github.com/galaxyproteomics/mzToSQLite
  license: GPL, Version 2.0
  summary: |
    Convert proteomics data files into a SQLite database.
